#!/bin/bash

VERSION=1.1
LONGVERSION=11

INSTALLER_LOCATION=https://github.com/STJr/Kart-Public/releases/download/v$VERSION/srb2kart-v$LONGVERSION-Installer.exe
PATCH_LOCATION=https://github.com/STJr/Kart-Public/releases/download/v$VERSION/srb2kart-v$LONGVERSION-patch.zip

TMP_DIR=$(mktemp -d)
cd $TMP_DIR
echo $TMP_DIR
# Installer
mkdir INSTALLER
cd INSTALLER

wget -O Installer.exe $INSTALLER_LOCATION
bsdtar xfv Installer.exe
install -Dm644 {music,textures,gfx,maps,sounds,chars,bonuschars}.kart srb2.srb /usr/share/games/SRB2Kart
cd ..

# Patch
mkdir PATCH
cd PATCH

wget -O patch.zip $PATCH_LOCATION
unzip patch.zip
install -Dm664 patch.kart /usr/share/games/SRB2Kart
cd ..

cd ..
rm -rf $TMP_DIR
